### ISSUE TITLE
Issue with create()

### ISSUE THREAD

**Issue by Neoblumbo** [gtalarico/pyairtable#167]
When trying to create a record using a dict some entries give back an error like this one:
```
Traceback (most recent call last):
  File "/Users/patricioguerra/Documents/PythonTests/atTesting.py", line 38, in <module>
    atTable.create(record)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyairtable/api/table.py", line 87, in create
    return super()._create(self.base_id, self.table_name, fields, typecast=typecast)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyairtable/api/abstract.py", line 134, in _create
    return self._request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyairtable/api/abstract.py", line 95, in _request
    return self._process_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyairtable/api/abstract.py", line 87, in _process_response
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyairtable/api/abstract.py", line 74, in _process_response
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: ('422 Client Error: Unprocessable Entity for url: [deleted for privacy]', '422 Client Error: Unprocessable Entity for url:[deleted for privacy]  [Error: {\'type\': \'INVALID_VALUE_FOR_COLUMN\', \'message\': \'Field "Brightness" cannot accept the provided value\'}]')
```
The value stored for these keys is in fact an integer when printed but error seems to indicate that airtable is receiving '}]' instead.

**Comment by Neoblumbo** [comment]
My script takes in JSON text, converts it to a dictionary (simply key value pairs, nothing nested) and then tried to create a new record with that dictionary. It writes many values without issues this is one of 4 keys which are giving and issue for some reason.

**Comment by gtalarico** [comment]
I would need a a reproducible example to be able to help.
Can you create a python script with a sample dictionary that reproduces the error?
And the description or screenshot of the base it's writing to? (Column names and types)


> `}]`

I think this is just part of the json content in the error message. I think it's just telling you
`Brightness" cannot accept the provided value`. This would happen if you attempt to pass a string to number field or other values that can't be cast

**Comment by Neoblumbo** [comment]
added you to a repo with the script and sample json used

**Comment by gtalarico** [comment]
What the aritable type of the `brightness` column? I don't see a field with that name in screenshots

**Comment by gtalarico** [comment]
In your sample file brightness is a number not string. Not sure if airtable casts numbers to string but i would try making sure all types match.

TBH his doesn't appear to be a library error but an issue with the values provided and what the API accept for those fields. 

I would try making sure types and columns align. You can use the curl samples provided by airtable docs as samples of JSON types wanted for your fields.

**Comment by Neoblumbo** [comment]
You're right. Thanks.
