### ISSUE TITLE
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### ISSUE THREAD

**Issue by clay-jona** [gtalarico/pyairtable#377]
Hi there,

Python version: 3.12
`pyairtable` version: tried form 2.1.0 to 2.3.3

I couldn't import `Api` class from the library with the following error. but it works fine with Python 3.11.
```
>>> from pyairtable import Api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/__init__.py", line 3, in <module>
    from .api import Api, Base, Table
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/api/__init__.py", line 1, in <module>
    from .api import Api
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/api/api.py", line 10, in <module>
    from pyairtable.api.enterprise import Enterprise
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/api/enterprise.py", line 4, in <module>
    from pyairtable.models._base import AirtableModel, update_forward_refs
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/models/__init__.py", line 12, in <module>
    from .comment import Comment
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pyairtable/models/comment.py", line 7, in <module>
    class Comment(
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pydantic/v1/main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/kb-py312/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by BAPCon** [comment]
I can't reproduce this error. **Except** when improperly building and using pyairtable by directly downloading the repo. I could reproduce a similar error in `update_forward_refs` where the missing `inflection` package is the culprit.
If you are pulling the repo directly, make sure all of the required packages are installed or build it properly. 

**Solutions**
### Install with pip
Seems like you're using conda, not sure how that may impact things. But if the problem occurs when using `pip` to manage the installation of `pyairtable`, let me know.
```
pip install pyairtable
```
### Other Solution: Build
Make sure you can use "make" in your terminal. If on Windows you may have to install GNUWin32 or choco.
Execute the following commands.
```
make setup
make test
```

**Comment by BAPCon** [comment]
Are you using a fresh virtual environment? It might be `pydantic` causing the issue if you have the incorrect version installed, or some versions of 3.12 are buggy with `pydantic`.
**Related Issue**
pydantic/pydantic#9637

**Comment by clay-jona** [comment]
Ah you're right. When i upgraded `pydantic` version from 2.6.4 to 2.8.2 it started working. Thanks guys! Closing this issue
